default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: unilog_dev

test:
  <<: *default
  database: unilog_test

production:
  <<: *default
  database: unilog_prod
